### ISSUE TITLE
Basic tag support

### ISSUE THREAD

**Issue by gnrfan** [rediscookbook/rediscookbook#2]
Each recipe has a list of tags in the metadata but they are not getting listed in the recipe header.

Each recipe should show a list of tags it is associated with and each tag should be a hyperlink to a page listing all of the recipes tagged that way.

**Comment by gnrfan** [comment]
Pull request sent.

**Comment by tnm** [comment]
awesome. merged!

**Comment by gnrfan** [comment]
After so much PHP and Python playing a bit with Ruby is always refreshing and fun :)
